### ISSUE TITLE
Calling setItems doesn't clear previous rows

### ISSUE THREAD

**Issue by nbabb** [TatuLund/bean-table#1]
Calling setItems a second time doesn't clear rows generated by a previous call.  BeanTable's override of setDataProvider calls reset, which in turn calls createRow and then addRow, but the rows generated by the previous call are not first removed.

Calling setDataProvider with a new provider also doesn't clear the old items.

If I precede the call to setItems with

```
myBeanTable.dataProvider.refreshAll()
```

I see that it calls the reset(false) method in BeanTable.java, setting bodyElement text to "" and reseting rows list, but the rendering doesn't remove the old rows.

**Comment by TatuLund** [comment]
Fixed by https://github.com/TatuLund/bean-table/commit/b2feef2a4b7bfeb3a44c4e8d149c5f98ea740039 in version 1.1.1
