### ISSUE TITLE
Cannot style row

### ISSUE THREAD

**Issue by nbabb** [TatuLund/bean-table#2]
I am trying to "highlight" - change the background color - of a row in the table that is in error.  I can style individual cells of the row in error, using the cell renderer, but am not clear on an approach for highlighting the entire row.  Any thoughts on this?  Perhaps I'll need to use javascript, as opposed to a pure CSS solution?  Any pseudo-code to accomplish this is appreciated.  Thanks.

Also, it would be nice to be able to access the Column's list, once it's been created.

**Comment by nbabb** [comment]
I addressed this with the following code. so the renderer is responsible for adding the 'row-error' class, and this picks up on this and highlights the parent row.

```
fun <T> BeanTable<T>.addErrorRowIndicator() =
    this.also {
        it.element.executeJs("requestAnimationFrame(function() { " +
                "var errorElements = document.getElementsByClassName('row-error');" +
                "for (let item of errorElements) {" +
                "   var row = item.closest('tr');" +
                "   row.style.backgroundColor = '#FF3D337F';" +
                "}" +
                "});")
    }
```

**Comment by TatuLund** [comment]
Yes, I have not built API for such thing yet (and many other small things). The add-on generates plain html table in DOM without shadow DOM, so from that perspective it should be possible to manipulate it in various ways like you did.

However adding class name provider API similar to Grid is technically quite straightforward to do, so I could consider that.

**Comment by TatuLund** [comment]
I added Table#setClassNameProvider and Column#setClassNameProvider methods in version 1.2.0 and couple of other improvements.
